### ISSUE TITLE
[Feature] Terminal-Like Persistent Command History

### ISSUE THREAD

**Issue by shubhdevelop** [DiceDB/playground-web#20]
It would be incredibly helpful to have a terminal-like command history feature, where commands entered in the terminal are saved persistently across a single sessions. This would allow users to recall, reuse, and modify previous commands without retyping them, significantly improving workflow efficiency.

**Proposed Behavior:**
- Commands entered are saved persistently and are available even when page reloads. Only to be cleared when users closes the Tab
- Users can navigate through their command history using arrow keys (↑/↓).

**Use Cases:**

- A developer experimenting with a series of commands can quickly navigate back to previous ones without retyping.
- Repetitive tasks can be quickly accessed, reducing the need for re-entering the same commands multiple times.
- Users can resume work easily after closing and reopening the interface.
    
  **Additional Context:**

This feature would greatly improve the user experience, especially for power users who frequently use the command line and rely on efficient recall mechanisms.

**Comment by lucifercr07** [comment]
@shubhdevelop assigned, thanks for contributing.
