### ISSUE TITLE
[Feature]: Debouncing required for SearchBox

### ISSUE THREAD

**Issue by Sanketmundada** [DiceDB/playground-web#23]
Debouncing the search input to avoid excessive search api calls.

This will help our search work effectively.

**Comment by anishkoulgi** [comment]
Hey @lucifercr07, I can pick this up!

**Comment by SahilLamba0008** [comment]
Hey, I would love to start work on this issue. Can you assign it to me ?

**Comment by lucifercr07** [comment]
@Sanketmundada there is no search API in works in frontend as of now. Closing this issue.
