### ISSUE TITLE
[Enhancement] - Terminal command history navigation based on current user input

### ISSUE THREAD

**Issue by prathameshkoshti** [DiceDB/playground-web#28]
Based on [#21 ](https://github.com/DiceDB/playground-web/issues/20)

### Current behaviour
User is able to navigate through the commands executed earlier, using up and down arrow keys

### Proposed Solution
Similarly to any shell that is present in the market, if user has typed something, based on the current input, command history to be shown which starts with current given input.
Eg. if user has executed following series of commands:
```
$ set name
$ get name
$ set gender
$ get gender
$ set birthYear
$ get birthYear
```
And then user types `get` in the terminal and tries to navigate through command history user shall see only commands starting with `get`, so the output may consist of following commands only:
```
$ get birthYear
$ get gender
$ get name
```

This makes UX more enhanced while navigating through command history

**Comment by prashant67690** [comment]
can you assign this issue to me
