### ISSUE TITLE
Implement CLI for DiceDB Playground UI

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-web#3]
## Description

DiceDB Playground is an interactive platform that allows users to experiment with DiceDB commands in a live environment, similar to the Go Playground. Users will be able to submit and execute commands directly through a web interface. The initial implementation will focus on enabling users to search for and trigger commands.  
For more details about DiceDB playground you can check [here](https://docs.google.com/document/d/1M5XfuOwQsRcl6g_VBr-FCLy71cnqCp7ulgyt6MsfESU/edit?usp=sharing).  

Implement the CLI component in DiceDB Playground UI as per the attached mockup, using NextJS as the framework and Bulma CSS for styling. The UI will include a mock CLI/Shell component with mock API responses in place.

**Note:** Implementation will be part of DiceDB playground frontend [repo](https://github.com/DiceDB/playground-web).
## Components to Implement

1. Shell/CLI Component:
	- Mimic a CLI environment where users can type and see responses.
	- Use dummy data to simulate command input/output (e.g., `SET` and `GET` commands).
	- Show remaining command triggers and cleanup timer with static values.

Technology Stack:
- Frontend Framework: NextJS
- CSS Framework: Bulma CSS

## Tasks

1. Setup the project using NextJS and configure Bulma CSS for styling.
2. Implement the **Shell/CLI component** with a scrollable interface for command history.
3. Implement command triggers and cleanup timer.
4. Use mock data for API responses.
5. Ensure responsiveness and a basic grid layout similar to the attached UI mockup.

**Note**: CLI component, command triggers and cleanup timer needs to be added as part of this issue.

<img width="1004" alt="Screenshot 2024-09-27 at 00 50 15" src="https://github.com/user-attachments/assets/3e76fe4b-584c-488f-9d8e-b9aa726fc244">

**Comment by lucifercr07** [comment]
Dependent on #2.

**Comment by N3XT14** [comment]
@lucifercr07 Can I work on this?

Thanks

**Comment by lucifercr07** [comment]
@N3XT14 assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
@N3XT14 please contribute along with #2 assignee to come up on initial struct for the repo.

**Comment by ritiksahni** [comment]
@N3XT14 What's your plan on implementing the CLI-interface?

Will this talk to a DiceDB instance via REST API just like Go Playground and output the result by parsing the JSON?

**Comment by lucifercr07** [comment]
@N3XT14 changes are in for the initial struct are merged now, you can start with integration with the API.

**Comment by N3XT14** [comment]
@ritiksahni Plan is to use rest api call and execute those commands. But for now I will start with mock url and once the api is ready to hit we can replace that with the url.

**Comment by lucifercr07** [comment]
@N3XT14 APIs are ready on backend side I believe, we can discuss on the format if you want so that's it's easy to render.

**Comment by Sanketmundada** [comment]
@lucifercr07 I can contribute in api integration part of search, If the api is ready

**Comment by prathameshkoshti** [comment]
Hey @lucifercr07, I would like to contribute in this project, maybe I can start with `/cli` api integration if the api is ready. Also, are you guys planning on implementing the husky in the repo?

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/playground-web/pull/9.
