### ISSUE TITLE
Refactor repo for consistency

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-web#35]
Fix below changes as part of playground-web repo:
- [ ] In `README` add details for node version requirement and other pre-requisite to run the project.
- [ ] In `README` add steps to run prettier scripts in case of Github workflow failure.
- [ ] Rename `Dockerfile_Backend` file to `PlaygroundMonoDockerfile`, also update the yml files for it.
- [ ] Rename `CLI` package to `Shell`
- [ ] Remove comment `// comment this to hide footer` from `page.tsx` file
- [ ] Update comments everywhere to `// comment` from `//comment`.
- [ ] Fix “Cleanup in :” and “Command left:” inconsistent styling. Also, it should be `Commands left`. Add a tool tip (i) button, next to both that tells what these limits are all about.
- [ ] Delete mockData.json file
- [ ] In api.ts, propagate the error to the user instead of just logging it to console. Show user the error that was emitted from the backend/mono.
- [ ] Instead of calling “blacklist”  var names update the word to “blocklist”.

**Comment by RishabhC-137** [comment]
I will take it

**Comment by lucifercr07** [comment]
@RishabhC-137 assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
Closing, merged as part of: https://github.com/DiceDB/playground-web/pull/59
