### ISSUE TITLE
Refactor repo implementation to a static site

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-web#37]
Changes required for this issue:
- [ ] Update the configuration to enable static export
- [ ] Remove Server-Side Rendering from components
- [ ] For dynamic routes, use getStaticPaths
- [ ] Adjust Data Fetching to client side data fetching
- [ ] Update Environment Variables accordingly
- [ ] Update Scripts in package.json
- [ ] Update README with required steps for build and run
- [ ] Test the Static Build locally and integrate with Github actions workflow.

**Comment by N3XT14** [comment]
@lucifercr07 Hi can you assign this to me.

Thanks

**Comment by lucifercr07** [comment]
@N3XT14 assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
Closing, merge as part of #50
