### ISSUE TITLE
Implement DiceDB Playground Search Component with Static Data

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-web#8]
## Description

DiceDB Playground is an interactive platform that allows users to experiment with DiceDB commands in a live environment, similar to the Go Playground. Users will be able to submit and execute commands directly through a web interface. The initial implementation will focus on enabling users to search for and trigger commands.  
For more details about DiceDB playground you can check [here](https://docs.google.com/document/d/1M5XfuOwQsRcl6g_VBr-FCLy71cnqCp7ulgyt6MsfESU/edit?usp=sharing).  

We need to implement a search component in the DiceDB Playground that uses a static map of command details. Each command will be represented by a key (command name) with a structured value containing the command's title, syntax, description (body), and documentation URL. This will simulate a search functionality without an API, and render relevant details for each command based on user input.

**Note:** Implementation will be part of DiceDB playground frontend [repo](https://github.com/DiceDB/playground-web).

## Map structure example

```
{
  "SET": {
    "title": "<b>SET</b>",
    "syntax": "SET key value [NX | XX] [EX seconds | PX milliseconds | EXAT unix-time-seconds | PXAT unix-time-milliseconds | KEEPTTL ]",
    "body": "The SET command in DiceDB is used to set the value of a key. If the key already holds a value, it is overwritten, regardless of its type. This is one of the most fundamental operations in DiceDB as it allows for both creating and updating key-value pairs.",
    "url": "https://dicedb-docs.netlify.app/commands/set/"
  },
  "GET": {
    "title": "<b>GET</b>",
    "syntax": "GET key",
    "body": "The GET command retrieves the value of a key. If the key does not exist, nil is returned.",
    "url": "https://dicedb-docs.netlify.app/commands/get/"
  }
}
```

## Tasks

1. Create Static Map of Command Data
- Define a static map where each command name (e.g., "SET", "GET") is the key, and the value is a struct containing the following fields:
    - Title: Command name with HTML formatting (for bold or other elements).
    - Syntax: Command syntax and options.
    - Body: Description of the command, including usage details.
    - URL: Link to the documentation for further reading.
- Store this map in a suitable location such as src/data/commandData.json or as a constant inside the search component.

2. Update Search Component
- Modify the `SearchComponent` in `src/components` to:
        - Perform a **prefix search** (e.g., typing "SE" should match all commands starting with "SE").
        - Filter the commands in the static map based on user input.
        - Use **case-insensitive** matching to ensure better search results.
- For each match, render the command’s **title**, **syntax**, **body**, and a link to the command’s documentation (using the **url** field).
- Ensure that as the user types, matching results are displayed dynamically in real-time.

3. Prefix Search Logic    
- Implement the prefix search logic to check for all command keys in the map that start with the user's input.
- Example: If the user types `SE`, the search component should match and display results for both `SET` and `SEARCH`.

4. **Handle Edge Cases**
- Display a "No Results Found" message if no commands match the user's input.
- Handle empty input by displaying no results or all available commands, depending on UX preference.

**Comment by rishavvajpayee** [comment]
Hey i can take this up @lucifercr07.

**Comment by rishavvajpayee** [comment]
PR: https://github.com/DiceDB/playground-web/pull/10
